### ISSUE TITLE
Accesss to pc-sync help

### ISSUE THREAD

**Issue by madtibo** [MozillaOnline/pc-sync-gaia-app#3]
I'm not going through the connection step (PC-phone using wifi)
And the help site (http://os.firefox.com.cn/pcsync.html) is down (nginx welcome page).
Where can I get some help to debug?

**Comment by chardis** [comment]
Hello madtib,

Thank you for your feedback. We fixed the issue. And now you can visit http://os.firefox.com.cn/pcsync.html to get some help.

BTW, because the project has not been updated for a long time, it maybe has some issues in the new OS version.

**Comment by madtibo** [comment]
Thank you very much!
I'm still using a very old OS. so it should work.
If I update, I'll keep you posted with any trouble  ;-)
